format_version: 10
pipelines:
  SamplePipeline:
    group: TimesheetsGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-7b21470:
        git: https://github.com/theeverestguy/MyRepo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Release:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Release:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - describe
                - --tags
                command: git
                run_if: passed
            - exec:
                arguments:
                - release.sh
                command: /bin/sh
                run_if: passed
