name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: export GITHUB_TOKEN=bee4927c09a8c343eb452a373c82ba883fb05994
    - run: export DEBUG=*
    - run: npm install semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec
    - run: npm install @semantic-release/git @semantic-release/release-notes-generator
    - run: npx semantic-release
